name: Test Python Server

on: [push]

jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
    - name: Run server in background
      run: |
        python server.py &
        sleep 5 # Give server time to start
    - name: Test server
      run: |
        curl -X POST http://localhost:8080/test -H "Content-Type: application/json" -d '{"message":"Hello, Server!"}'
